/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package netlink.swig;

public class capi {
    public static long if_nametoindex(String ifname) {
        return capiJNI.if_nametoindex(ifname);
    }

    public static String nl_geterror(int arg0) {
        return capiJNI.nl_geterror(arg0);
    }

    public static int nl_connect(SWIGTYPE_p_nl_sock arg0, int arg1) {
        return capiJNI.nl_connect(SWIGTYPE_p_nl_sock.getCPtr(arg0), arg1);
    }

    public static void nl_close(SWIGTYPE_p_nl_sock arg0) {
        capiJNI.nl_close(SWIGTYPE_p_nl_sock.getCPtr(arg0));
    }

    public static SWIGTYPE_p_nl_sock nl_socket_alloc() {
        long cPtr = capiJNI.nl_socket_alloc();
        return (cPtr == 0) ? null : new SWIGTYPE_p_nl_sock(cPtr, false);
    }

    public static void nl_socket_free(SWIGTYPE_p_nl_sock arg0) {
        capiJNI.nl_socket_free(SWIGTYPE_p_nl_sock.getCPtr(arg0));
    }

    public static long tc_str2handle(String name) {
        return capiJNI.tc_str2handle(name);
    }

    public static void rtnl_tc_set_ifindex(SWIGTYPE_p_rtnl_tc arg0, int arg1) {
        capiJNI.rtnl_tc_set_ifindex(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static int rtnl_tc_get_ifindex(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_ifindex(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static void rtnl_tc_set_mtu(SWIGTYPE_p_rtnl_tc arg0, long arg1) {
        capiJNI.rtnl_tc_set_mtu(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static long rtnl_tc_get_mtu(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_mtu(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static void rtnl_tc_set_mpu(SWIGTYPE_p_rtnl_tc arg0, long arg1) {
        capiJNI.rtnl_tc_set_mpu(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static long rtnl_tc_get_mpu(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_mpu(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static void rtnl_tc_set_overhead(SWIGTYPE_p_rtnl_tc arg0, long arg1) {
        capiJNI.rtnl_tc_set_overhead(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static long rtnl_tc_get_overhead(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_overhead(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static void rtnl_tc_set_linktype(SWIGTYPE_p_rtnl_tc arg0, long arg1) {
        capiJNI.rtnl_tc_set_linktype(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static long rtnl_tc_get_linktype(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_linktype(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static void rtnl_tc_set_handle(SWIGTYPE_p_rtnl_tc arg0, long arg1) {
        capiJNI.rtnl_tc_set_handle(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static long rtnl_tc_get_handle(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_handle(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static void rtnl_tc_set_parent(SWIGTYPE_p_rtnl_tc arg0, long arg1) {
        capiJNI.rtnl_tc_set_parent(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static long rtnl_tc_get_parent(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_parent(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static int rtnl_tc_set_kind(SWIGTYPE_p_rtnl_tc arg0, String arg1) {
        return capiJNI.rtnl_tc_set_kind(SWIGTYPE_p_rtnl_tc.getCPtr(arg0), arg1);
    }

    public static String rtnl_tc_get_kind(SWIGTYPE_p_rtnl_tc arg0) {
        return capiJNI.rtnl_tc_get_kind(SWIGTYPE_p_rtnl_tc.getCPtr(arg0));
    }

    public static SWIGTYPE_p_rtnl_tc qdisc2tc(SWIGTYPE_p_rtnl_qdisc qdisc) {
        long cPtr = capiJNI.qdisc2tc(SWIGTYPE_p_rtnl_qdisc.getCPtr(qdisc));
        return (cPtr == 0) ? null : new SWIGTYPE_p_rtnl_tc(cPtr, false);
    }

    public static SWIGTYPE_p_rtnl_tc class2tc(SWIGTYPE_p_rtnl_class cl) {
        long cPtr = capiJNI.class2tc(SWIGTYPE_p_rtnl_class.getCPtr(cl));
        return (cPtr == 0) ? null : new SWIGTYPE_p_rtnl_tc(cPtr, false);
    }

    public static SWIGTYPE_p_rtnl_tc cls2tc(SWIGTYPE_p_rtnl_cls cls) {
        long cPtr = capiJNI.cls2tc(SWIGTYPE_p_rtnl_cls.getCPtr(cls));
        return (cPtr == 0) ? null : new SWIGTYPE_p_rtnl_tc(cPtr, false);
    }

    public static SWIGTYPE_p_rtnl_qdisc rtnl_qdisc_alloc() {
        long cPtr = capiJNI.rtnl_qdisc_alloc();
        return (cPtr == 0) ? null : new SWIGTYPE_p_rtnl_qdisc(cPtr, false);
    }

    public static void rtnl_qdisc_put(SWIGTYPE_p_rtnl_qdisc arg0) {
        capiJNI.rtnl_qdisc_put(SWIGTYPE_p_rtnl_qdisc.getCPtr(arg0));
    }

    public static int rtnl_qdisc_add(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_qdisc arg1, int arg2) {
        return capiJNI.rtnl_qdisc_add(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_qdisc.getCPtr(arg1), arg2);
    }

    public static int rtnl_qdisc_update(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_qdisc arg1, SWIGTYPE_p_rtnl_qdisc arg2, int arg3) {
        return capiJNI.rtnl_qdisc_update(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_qdisc.getCPtr(arg1), SWIGTYPE_p_rtnl_qdisc.getCPtr(arg2), arg3);
    }

    public static int rtnl_qdisc_delete(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_qdisc arg1) {
        return capiJNI.rtnl_qdisc_delete(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_qdisc.getCPtr(arg1));
    }

    public static SWIGTYPE_p_rtnl_class rtnl_class_alloc() {
        long cPtr = capiJNI.rtnl_class_alloc();
        return (cPtr == 0) ? null : new SWIGTYPE_p_rtnl_class(cPtr, false);
    }

    public static void rtnl_class_put(SWIGTYPE_p_rtnl_class arg0) {
        capiJNI.rtnl_class_put(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_class_add(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_class arg1, int arg2) {
        return capiJNI.rtnl_class_add(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_class.getCPtr(arg1), arg2);
    }

    public static int rtnl_class_delete(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_class arg1) {
        return capiJNI.rtnl_class_delete(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_class.getCPtr(arg1));
    }

    public static SWIGTYPE_p_rtnl_cls rtnl_cls_alloc() {
        long cPtr = capiJNI.rtnl_cls_alloc();
        return (cPtr == 0) ? null : new SWIGTYPE_p_rtnl_cls(cPtr, false);
    }

    public static void rtnl_cls_put(SWIGTYPE_p_rtnl_cls arg0) {
        capiJNI.rtnl_cls_put(SWIGTYPE_p_rtnl_cls.getCPtr(arg0));
    }

    public static int rtnl_cls_add(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_cls arg1, int arg2) {
        return capiJNI.rtnl_cls_add(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_cls.getCPtr(arg1), arg2);
    }

    public static int rtnl_cls_delete(SWIGTYPE_p_nl_sock arg0, SWIGTYPE_p_rtnl_cls arg1, int arg2) {
        return capiJNI.rtnl_cls_delete(SWIGTYPE_p_nl_sock.getCPtr(arg0), SWIGTYPE_p_rtnl_cls.getCPtr(arg1), arg2);
    }

    public static void rtnl_cls_set_prio(SWIGTYPE_p_rtnl_cls arg0, int arg1) {
        capiJNI.rtnl_cls_set_prio(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_cls_get_prio(SWIGTYPE_p_rtnl_cls arg0) {
        return capiJNI.rtnl_cls_get_prio(SWIGTYPE_p_rtnl_cls.getCPtr(arg0));
    }

    public static void rtnl_cls_set_protocol(SWIGTYPE_p_rtnl_cls arg0, int arg1) {
        capiJNI.rtnl_cls_set_protocol(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_cls_get_protocol(SWIGTYPE_p_rtnl_cls arg0) {
        return capiJNI.rtnl_cls_get_protocol(SWIGTYPE_p_rtnl_cls.getCPtr(arg0));
    }

    public static void rtnl_u32_set_handle(SWIGTYPE_p_rtnl_cls arg0, int arg1, int arg2, int arg3) {
        capiJNI.rtnl_u32_set_handle(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1, arg2, arg3);
    }

    public static int rtnl_u32_set_classid(SWIGTYPE_p_rtnl_cls arg0, long arg1) {
        return capiJNI.rtnl_u32_set_classid(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_u32_set_divisor(SWIGTYPE_p_rtnl_cls arg0, long arg1) {
        return capiJNI.rtnl_u32_set_divisor(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_u32_set_link(SWIGTYPE_p_rtnl_cls arg0, long arg1) {
        return capiJNI.rtnl_u32_set_link(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_u32_set_hashtable(SWIGTYPE_p_rtnl_cls arg0, long arg1) {
        return capiJNI.rtnl_u32_set_hashtable(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_u32_set_hashmask(SWIGTYPE_p_rtnl_cls arg0, long arg1, long arg2) {
        return capiJNI.rtnl_u32_set_hashmask(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1, arg2);
    }

    public static int rtnl_u32_set_cls_terminal(SWIGTYPE_p_rtnl_cls arg0) {
        return capiJNI.rtnl_u32_set_cls_terminal(SWIGTYPE_p_rtnl_cls.getCPtr(arg0));
    }

    public static int rtnl_u32_set_flags(SWIGTYPE_p_rtnl_cls arg0, int arg1) {
        return capiJNI.rtnl_u32_set_flags(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1);
    }

    public static int rtnl_u32_add_key_uint8(SWIGTYPE_p_rtnl_cls arg0, short arg1, short arg2, int arg3, int arg4) {
        return capiJNI.rtnl_u32_add_key_uint8(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1, arg2, arg3, arg4);
    }

    public static int rtnl_u32_add_key_uint16(SWIGTYPE_p_rtnl_cls arg0, int arg1, int arg2, int arg3, int arg4) {
        return capiJNI.rtnl_u32_add_key_uint16(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1, arg2, arg3, arg4);
    }

    public static int rtnl_u32_add_key_uint32(SWIGTYPE_p_rtnl_cls arg0, long arg1, long arg2, int arg3, int arg4) {
        return capiJNI.rtnl_u32_add_key_uint32(SWIGTYPE_p_rtnl_cls.getCPtr(arg0), arg1, arg2, arg3, arg4);
    }

    public static long rtnl_htb_get_rate2quantum(SWIGTYPE_p_rtnl_qdisc arg0) {
        return capiJNI.rtnl_htb_get_rate2quantum(SWIGTYPE_p_rtnl_qdisc.getCPtr(arg0));
    }

    public static int rtnl_htb_set_rate2quantum(SWIGTYPE_p_rtnl_qdisc arg0, long arg1) {
        return capiJNI.rtnl_htb_set_rate2quantum(SWIGTYPE_p_rtnl_qdisc.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_defcls(SWIGTYPE_p_rtnl_qdisc arg0) {
        return capiJNI.rtnl_htb_get_defcls(SWIGTYPE_p_rtnl_qdisc.getCPtr(arg0));
    }

    public static int rtnl_htb_set_defcls(SWIGTYPE_p_rtnl_qdisc arg0, long arg1) {
        return capiJNI.rtnl_htb_set_defcls(SWIGTYPE_p_rtnl_qdisc.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_prio(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_prio(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_htb_set_prio(SWIGTYPE_p_rtnl_class arg0, long arg1) {
        return capiJNI.rtnl_htb_set_prio(SWIGTYPE_p_rtnl_class.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_rate(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_rate(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_htb_set_rate(SWIGTYPE_p_rtnl_class arg0, long arg1) {
        return capiJNI.rtnl_htb_set_rate(SWIGTYPE_p_rtnl_class.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_ceil(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_ceil(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_htb_set_ceil(SWIGTYPE_p_rtnl_class arg0, long arg1) {
        return capiJNI.rtnl_htb_set_ceil(SWIGTYPE_p_rtnl_class.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_rbuffer(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_rbuffer(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_htb_set_rbuffer(SWIGTYPE_p_rtnl_class arg0, long arg1) {
        return capiJNI.rtnl_htb_set_rbuffer(SWIGTYPE_p_rtnl_class.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_cbuffer(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_cbuffer(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_htb_set_cbuffer(SWIGTYPE_p_rtnl_class arg0, long arg1) {
        return capiJNI.rtnl_htb_set_cbuffer(SWIGTYPE_p_rtnl_class.getCPtr(arg0), arg1);
    }

    public static long rtnl_htb_get_quantum(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_quantum(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

    public static int rtnl_htb_set_quantum(SWIGTYPE_p_rtnl_class arg0, long arg1) {
        return capiJNI.rtnl_htb_set_quantum(SWIGTYPE_p_rtnl_class.getCPtr(arg0), arg1);
    }

    public static int rtnl_htb_get_level(SWIGTYPE_p_rtnl_class arg0) {
        return capiJNI.rtnl_htb_get_level(SWIGTYPE_p_rtnl_class.getCPtr(arg0));
    }

}
